<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN_obsolete" Id="{b128b248-c142-427a-98d0-25b88a13d8f0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN_obsolete
VAR
	robot1 : RobotLadder;
	robot2 : Robot;
	sensorBlock AT %I* : BIT8_ARRAY;
	//test : MDP5001_0_A368DC73;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[robot1();
robot2();]]></ST>
    </Implementation>
    <LineIds Name="MAIN_obsolete">
      <LineId Id="29" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>