<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{98b5f675-dd89-4510-87f3-6dab8b969718}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	suctionLeft : PneumaticUnit;
	suctionRight : PneumaticUnit;
	
	enableL : BOOL;
	enableR : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[suctionLeft.enable := enableL;
suctionRight.enable := enableR;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="12" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>